services:
  api:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - 8080:8080   
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__AppDbConnection=Server=database;Database=Jobfinder;User=sa;Password=Reza1234@;TrustServerCertificate=True;
    depends_on:
      - database
      - minio
      
        
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Jobfinder
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Reza1234@
  minio:
    image: minio/minio
    container_name: objectStorage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data


volumes:
  minio-data: