services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Jobfinder
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Reza1234@