@Host=https://localhost:7093
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxOTcxODhjZC1iMDA5LTQxNWUtNDg3ZC0wOGRkNzVmNzM1ZDUiLCJqdGkiOiJjYTBhZDJkNC1mMGU4LTQ0ZGUtYTlmNi01NzczZjM4MWQzMDQiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDkzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiRW1wbG95ZXIiLCJleHAiOjE3NDY2Mzc5MTIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjcwOTMifQ.pn0BmExLb2ebC2-YqzRmTvQlHgDzxp3fphbPdUtxgn8
@jobSeeker =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZWRhYzQwNi02OTA1LTQ3NWItNDg3Yy0wOGRkNzVmNzM1ZDUiLCJqdGkiOiJhZmVjYmRkZC1hZjkwLTRlNWItOTU2Yy0wNTFhMjU5ODczNDYiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDkzIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiSm9iU2Vla2VyIiwiZXhwIjoxNzQ2NjM4OTY0LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDkzIn0.rS8_BLaQH9Ggmfm4SUdsH8k_dInNF2gu1MUdIWuMHlM
@refresh=CP46F/4eLvu96JFnxl9X7r8Bz6UeHr/Kc+9ahUEj9DA=
POST {{Host}}/api/identity/register
Accept: application/json
Content-Type: application/json

{
   "email":"rezajafarpoor009@gmail.com",
   "password":"Reza1234@",
   "userType":"Jobseeker"
}

###
POST {{Host}}/api/identity/login
Accept: application/json
Content-Type: application/json

{
   "email":"rezajafarpoor222@gmail.com",
   "password":"Reza1234@",
   "userType":"Jobseeker"
}
###
POST {{Host}}/api/cvs
Authorization: Bearer {{jobSeeker}}
Accept: application/json
Content-Type: application/json

{
  "location": {
    "province": "khosezstan",
    "city": "ahvaz",
    "address": "golestan"
  },
  "birthDay": "1999-12-12",
  "maximumSalary": 16,
  "minimumSalary": 12,
  "status":0,
  "firstName":"reza",
  "lastName":"jafarpoor"
}
###
GET {{Host}}/api/cvs
Accept: application/json
###
GET {{Host}}/api/cvs/{id}
###
POST {{Host}}/api/jobOffers
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "jobName": "Backend developer",
  "jobDescription": "a great job in our company",
  "jobDetails": {
    "contractType": 0,
    "workingDatsAndHours": {
      "from": 7,
      "to": 4,
      "startingHour": 8,
      "finishingHour":15
    },
    "isRemote": false,
    "location": {
      "province": "khosezstan",
      "city": "ahvaz",
      "address": "golestan"
    },
    "minimumAge": 18,
    "maximumAge": 32
  },
  "salary": {
    "from": 22,
    "to": 42
  },
  "category": "Software"
}
###

POST {{Host}}/api/company 
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "companyName": "my company",
  "websiteAddress": "www.myCompany.com",
  "location": {
    "province": "khosezstan",
    "city": "Ahvaz",
    "address": "golestan"
  },
  "sizeOfCompany": 12,
  "description": "my company is great"
}
###
GET{{Host}}/api/jobOffers
Accept: application/json
###
POST {{Host}}/api/jobOffers/fc2a51d9-9425-4c92-9bc3-08dd75f7e5f7/applications/fced9940-7b53-48c9-68a4-08dd75fa4f9c
Accept: application/json
Authorization: Bearer {{token}}
Content-Type:  application/json

{
 "status":1
}

###
GET {{Host}}/api/jobOffers/fc2a51d9-9425-4c92-9bc3-08dd75f7e5f7/applications
Accept: application/json
Authorization: Bearer {{token}}

###
POST{{Host}}/api/identity/refresh
Accept: application/json
Content-Type: application/json

"{{refresh}}"
###

POST{{Host}}/api/identity/forget
Accept: application/json
Content-Type: application/json

{
  "email": "rezajafarpoor222@gmail.com"
}
###
POST{{Host}}/api/identity/reset
Accept: application/json
Content-Type: application/json

{
  "email": "rezajafarpoor222@gmail.com",
  "token": "CfDJ8GMEA3E5+wJMncBsI0KeoyF09xxpAri/0vNPRve5rfOF2DHjJevmc1xrRCQLwePdEfvaiXmHed2FFYo0VwcAx5KlzA+NTshWTJreI5LC0dqI7vKm53emw/VVur0JrJcs8HRQmrH7aKYzuq5j1Fps2LsBWOYYJg+XQBuKuA6A4YTMo/AcWsThTJ2XbMK8+O1tM12979wqtRs8WOR2/IHLbUTFj3Q8Ls51erQZp5Z3x6PG",
  "newPassword": "Reza6692@"
}
###
GET{{Host}}/api/test
###