@Host=https://localhost:7093
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmZDQ3NTljMC05NjJhLTQ4MDgtMDM1My0wOGRkNzM3NzcyNmEiLCJqdGkiOiI3ZGY3M2M2My05MGUyLTQ4ZWQtOTFlYy1lZDZlY2MzOWEwMWMiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo3MDkzIiwiZXhwIjoxNzQ2MzYzNTE4LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDkzIn0.9dJK6Ys4Y-Adml5VqR8Qhpjk-yherXyIkGtjT548nQI
POST {{Host}}/api/identity/register
Accept: application/json
Content-Type: application/json

{
   "email":"reza@gmail.com",
   "password":"Reza1234@",
   "userType":"Employer"
}

###z`
POST {{Host}}/api/identity/login
Accept: application/json
Content-Type: application/json

{
   "email":"reza@gmail.com",
   "password":"Reza1234@",
   "userType":"Employer"
}
###
POST {{Host}}/api/cvs
Accept: application/json
Authorization: Bearer 
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "location": {
    "province": "khosezstan",
    "city": "ahvaz",
    "address": "golestan"
  },
  "birthDay": "1999-12-12",
  "maximumSalary": 16,
  "minimumSalary": 12,
  "status":0,
  "firstName":"reza",
  "lastName":"jafarpoor"
  
}
###
GET {{Host}}/api/cvs
Accept: application/json
###
GET {{Host}}/api/cvs/{id}
###
POST {{Host}}/api/jobOffer
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
  "jobName": "Backend developer",
  "jobDescription": "a great job in our company",
  "jobDetails": {
    "contractType": 0,
    "workingDatsAndHours": {
      "from": 7,
      "to": 4,
      "startingHour": 8,
      "finishingHour":15
    },
    "isRemote": false,
    "location": {
      "province": "khosezstan",
      "city": "ahvaz",
      "address": "golestan"
    },
    "minimumAge": 18,
    "maximumAge": 32
  },
  "salary": {
    "from": 22,
    "to": 42
  },
  "category": "Software"
}
###

POST {{Host}}/api/company 
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "companyName": "my company",
  "websiteAddress": "www.myCompany.com",
  "location": {
    "province": "khosezstan",
    "city": "Ahvaz",
    "address": "golestan"
  },
  "sizeOfCompany": 12,
  "description": "my company is great"
}
###
GET{{Host}}/api/test
